repos:
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black
  #       exclude: ^xieffect/(__lib__|test|alembic|communication)
  #       # communication is temporarily deprecated
  #       # TODO mb use the hook
  #       files: ^xieffect
  #       language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        exclude: ^xieffect/(__lib__|test/chatting.*|.*2|alembic|communication)  # communication is temporarily deprecated
        files: ^xieffect
        args: [ "--config=setup.cfg" ]
        additional_dependencies:
          # Basics
          - flake8
          - flake8-bugbear
          - wemake-python-styleguide  # TODO this does not work fully!

          # Bugs
          - flake8-2020
          - flake8-alfred
          - flake8-bugbear
          - flake8-debugger
          - flake8-string-format
          - flake8-unused-arguments
          # TODO - flake8-encodings
          # TODO - flake8-secure-coding-standard
          # - flake8-warnings  # failed to install
          # - flake8-useless-assert  # failed to install & unusable with pytest

          # Simplifications
          - dlint
          - flake8-pie
          - flake8-simplify

          # Imports
          - flake8-tidy-imports
          - flake8-obey-import-goat
          # - flake8-future-import  # too much screaming
          # - flake8-import-order  # does not work properly

          # Style
          - flake8-broken-line
          - flake8-comprehensions
          - flake8-multiline-containers
          - flake8-return
          - flake8-sql
          - mccabe
          - pycodestyle
          # - flake8-class-attributes-order  # too much screaming
          # - flake8-commas  # too much screaming
          # - flake8-literal  # black does this, but with double quotes (mb look into docs)
          # - flake8-scream  # too much screaming and that's the point
          # - flake8-strict  # failed to install

          # Naming
          - flake8-builtins
          - flake8-test-name
          - pep8-naming
          # - flake8-functions-names  # screams too much
          # - flake8-variables-names  # screams at tables' ids

          # Comments
          - flake8-comments
          - flake8-eradicate
          - flake8-executable
          - flake8-noqa
          # TODO - flake8-coding  # wants encoding comments in every file

          # Typing
          - flake8-annotations-coverage
          - flake8-future-annotations
          - flake8-new-union-types
          - flake8-pep585
          - flake8-pep604
          - flake8-typing-imports
          # TODO - flake8-annotations
          # TODO - flake8-type-checking (https://github.com/snok/flake8-type-checking)

          # Complexity
          - flake8-annotations-complexity
          # TODO - flake8-cognitive-complexity
          # TODO - flake8-expression-complexity
          # - cohesion  # screams at all Resources
          # - flake8-functions  # weird
          # - flake8-length  # built-in & handed over to black

          # Random
          - flake8-implicit-str-concat
          - flake8-use-fstring
          # TODO - flake8-use-pathlib
          # - flake8-newspaper-style  # failed to install
          # - flake8-print  # screams too much
          # - flake8-requirements  # failed to install

          # Tools
          # - hacking  # failed to install
          # - flakehell  # failed to install
          # TODO - flake8-pylint (raw lib, not wrapper: https://github.com/PyCQA/pylint/ ?)
