repos:
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black
  #       exclude: ^xieffect/(__lib__|test|alembic|communication)
  #       # communication is temporarily deprecated
  #       # TODO mb use the hook
  #       files: ^xieffect
  #       language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        exclude: ^xieffect/(__lib__|test/chatting.*|.*2|alembic|communication)  # communication is temporarily deprecated
        files: ^xieffect
        args: [ "--config=setup.cfg" ]
        additional_dependencies:
          # Basics
          - flake8
          - wemake-python-styleguide
          - flake8-bugbear
