repos:
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black
  #       exclude: ^xieffect/(__lib__|alembic|test|communication)  # communication is temporarily deprecated
  #       files: ^xieffect
  #       language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        exclude: ^xieffect/(__lib__|alembic|test|communication)  # communication is temporarily deprecated
        files: ^xieffect
        args: [ "--config=setup.cfg" ]
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
