repos:
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black
  #       exclude: ^xieffect/(__lib__|test|alembic|communication)
  #       # communication is temporarily deprecated
  #       # TODO mb use the hook
  #       files: ^xieffect
  #       language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        exclude: ^xieffect/(__lib__|test/chatting.*|.*2|alembic|communication)  # communication is temporarily deprecated
        files: ^xieffect
        args: [ "--config=setup.cfg" ]
        additional_dependencies:
          # Basics
          - flake8
          - wemake-python-styleguide  # TODO this does not work fully!
          - flake8-bugbear

          # Bugs
          - flake8-2020
          - flake8-alfred
          - flake8-bugbear
          - flake8-debugger
          - flake8-string-format
          - flake8-unused-arguments
          # TODO - flake8-encodings
          # TODO - flake8-secure-coding-standard
          # - flake8-warnings
          # - flake8-useless-assert  # unusable with pytest

          # Simplifications
          - dlint
          - flake8-pie
          - flake8-simplify

          # Imports
          - flake8-tidy-imports
          - flake8-obey-import-goat
          # - flake8-future-import  # too much screaming
          # - flake8-import-order  # does not work properly

          # Style
          - mccabe
          - pycodestyle
          - flake8-broken-line
          - flake8-comprehensions
          - flake8-return
          - flake8-sql
          - flake8-multiline-containers
          # - flake8-class-attributes-order
          # - flake8-commas  # too much screaming
          # - flake8-literal  # black does this, but with double quotes (mb look into docs)
          # - flake8-scream  # too much screaming and that's the point
          # - flake8-strict  # failed to install

          # Naming
          - flake8-builtins
          - pep8-naming
          # - flake8-test-name
          # - flake8-functions-names  # screams too much
          # - flake8-variables-names  # screams at tables' ids

          # Comments
          - flake8-comments
          - flake8-eradicate
          - flake8-executable
          # - flake8-coding  # wants encoding comments in every file
          # - flake8-noqa  # failed to install
