version: "3"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
