"""cd-videochat-tools

Revision ID: 217fa30f86eb
Revises: 666a1198f0a7
Create Date: 2022-12-10 16:18:38.767328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217fa30f86eb'
down_revision = '666a1198f0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cs_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name=op.f('fk_cs_chat_messages_community_id_community'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_cs_chat_messages_sender_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cs_chat_messages'))
    )
    op.create_table('cs_chat_participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name=op.f('fk_cs_chat_participants_community_id_community'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cs_chat_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'community_id', name=op.f('pk_cs_chat_participants'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cs_chat_participants')
    op.drop_table('cs_chat_messages')
    # ### end Alembic commands ###
