"""user-handle-1

Revision ID: 3693bda32ddc
Revises: 73df9bf89b44
Create Date: 2022-11-20 23:33:51.452156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3693bda32ddc'
down_revision = '73df9bf89b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_communities_users_avatar_id_files'), 'files', ['avatar_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_handle'), ['handle'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_handle'))
        batch_op.drop_column('birthday')
        batch_op.drop_column('handle')

    with op.batch_alter_table('communities_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_communities_users_avatar_id_files'), type_='foreignkey')
        batch_op.drop_column('avatar_id')

    # ### end Alembic commands ###
