"""user_themes

Revision ID: 402b
Revises: 402
Create Date: 2023-06-11 13:58:02.711851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402b'
down_revision = '402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), server_default="system", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
