"""new-pages

Revision ID: 408
Revises: e47946082c0a
Create Date: 2023-05-08 14:01:27.905379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '408'
down_revision = 'e47946082c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cs_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opened', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cs_tasks_closed'), ['closed'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_tasks_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_tasks_opened'), ['opened'], unique=False)
        batch_op.drop_column('updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cs_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_cs_tasks_opened'))
        batch_op.drop_index(batch_op.f('ix_cs_tasks_created'))
        batch_op.drop_index(batch_op.f('ix_cs_tasks_closed'))
        batch_op.drop_column('closed')
        batch_op.drop_column('opened')

    # ### end Alembic commands ###
