"""discussions-base

Revision ID: 410
Revises: 402b
Create Date: 2023-06-12 20:51:37.016735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410'
down_revision = '402b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussions'))
    )
    op.create_table('ds_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], name=op.f('fk_ds_messages_discussion_id_discussions'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_ds_messages_sender_id_users'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ds_messages'))
    )
    op.create_table('ds_message_files',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_ds_message_files_file_id_files'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ds_messages.id'], name=op.f('fk_ds_message_files_message_id_ds_messages'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'file_id', name=op.f('pk_ds_message_files'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ds_message_files')
    op.drop_table('ds_messages')
    op.drop_table('discussions')
    # ### end Alembic commands ###
