"""tests-base

Revision ID: 413
Revises: 410
Create Date: 2023-08-06 12:52:52.671216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413'
down_revision = '410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cs_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cs_tasks.id'], name=op.f('fk_cs_tests_id_cs_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cs_tests'))
    )
    op.create_table('cs_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('SIMPLE', 'DETAILED', 'CHOICE', name='questionkind'), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['cs_tests.id'], name=op.f('fk_cs_questions_test_id_cs_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cs_questions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cs_questions')
    op.drop_table('cs_tests')
    # ### end Alembic commands ###
