"""limit-invitations

Revision ID: 415
Revises: 413
Create Date: 2023-08-06 12:58:38.114243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415'
down_revision = '413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('invite_count')

    with op.batch_alter_table('cs_invitations', schema=None) as batch_op:
        batch_op.create_index('hash_index_cs_invites_community_id', ['community_id'], unique=False, postgresql_using='hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cs_invitations', schema=None) as batch_op:
        batch_op.drop_index('hash_index_cs_invites_community_id', postgresql_using='hash')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_count', sa.INTEGER(), autoincrement=False, nullable=False, server_default="0"))

    # ### end Alembic commands ###
