"""current-roles

Revision ID: 416
Revises: 415
Create Date: 2023-09-01 02:46:36.179698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '416'
down_revision = '415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cs_participant_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cs_participant_roles_role_id_cs_roles', type_='foreignkey')
        batch_op.drop_constraint('fk_cs_participant_roles_participant_id_community_participant', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cs_participant_roles_role_id_cs_roles'), 'cs_roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_cs_participant_roles_participant_id_community_participant'), 'community_participant', ['participant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cs_role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cs_role_permissions_role_id_cs_roles', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cs_role_permissions_role_id_cs_roles'), 'cs_roles', ['role_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cs_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cs_roles_community_id_community', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cs_roles_community_id_community'), 'community', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cs_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cs_roles_community_id_community'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cs_roles_community_id_community', 'community', ['community_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('cs_role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cs_role_permissions_role_id_cs_roles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cs_role_permissions_role_id_cs_roles', 'cs_roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('cs_participant_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cs_participant_roles_participant_id_community_participant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cs_participant_roles_role_id_cs_roles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cs_participant_roles_participant_id_community_participant', 'community_participant', ['participant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_cs_participant_roles_role_id_cs_roles', 'cs_roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
