"""community-base

Revision ID: 435f3661fd58
Revises: dab3b28bcb0f
Create Date: 2022-04-14 19:10:18.584245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435f3661fd58'
down_revision = 'dab3b28bcb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invite_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('BASE', 'OWNER', name='participantrole'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_participant',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('BASE', 'OWNER', name='participantrole'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_participant')
    op.drop_table('community_invites')
    op.drop_table('community')
    # ### end Alembic commands ###
