"""files

Revision ID: 4a0685f4a618
Revises: f97329c355f9
Create Date: 2022-08-17 00:17:02.886644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a0685f4a618'
down_revision = 'f97329c355f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('uploader_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_files_uploader_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
