"""files

Revision ID: 4a0685f4a618
Revises: f97329c355f9
Create Date: 2022-08-17 00:17:02.886644

"""

# revision identifiers, used by Alembic.
revision = '4a0685f4a618'
down_revision = 'f97329c355f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
