"""mub-2

Revision ID: 64b239c3d2ae
Revises: 28e18c527412
Create Date: 2022-08-12 02:57:38.468037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b239c3d2ae'
down_revision = '28e18c527412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mub-sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mub-sections'))
    )
    with op.batch_alter_table('mub-moderators', schema=None) as batch_op:
        batch_op.alter_column('superuser', new_column_name='super')

    with op.batch_alter_table('mub-permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_mub-permissions_name', type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_mub-permissions_section_id_mub-sections'), 'mub-sections', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mub-permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mub-permissions_section_id_mub-sections'), type_='foreignkey')
        batch_op.create_unique_constraint('uq_mub-permissions_name', ['name'])
        batch_op.drop_column('section_id')

    with op.batch_alter_table('mub-moderators', schema=None) as batch_op:
        batch_op.alter_column('super', new_column_name='superuser')

    op.drop_table('mub-sections')
    # ### end Alembic commands ###
