"""new-cs-metadata

Revision ID: 7250fb010703
Revises: 928f100cf232
Create Date: 2023-03-18 15:51:53.051554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7250fb010703'
down_revision = '928f100cf232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('avatar_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_community_avatar_id_files'), 'files', ['avatar_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # Requires a database wipe
    op.drop_table('community_lists')
    with op.batch_alter_table('community_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_community_participant_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_community_participant_prev_id_community_participant'), 'community_participant', ['prev_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_community_participant_next_id_community_participant'), 'community_participant', ['next_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_community_participant_user_id_communities_users'), 'communities_users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_community_avatar_id_files'), type_='foreignkey')
        batch_op.drop_column('avatar_id')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('community_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_community_participant_user_id_communities_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_community_participant_next_id_community_participant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_community_participant_prev_id_community_participant'), type_='foreignkey')
        batch_op.create_foreign_key('fk_community_participant_user_id_users', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('next_id')
        batch_op.drop_column('prev_id')

    op.create_table('community_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name='fk_community_lists_community_id_community', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['communities_users.id'], name='fk_community_lists_user_id_communities_users', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_community_lists')
    )
    # ### end Alembic commands ###
