"""cleanup

Revision ID: 7ecc867e7b7c
Revises: 4a0685f4a618
Create Date: 2022-10-19 01:30:25.582768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecc867e7b7c'
down_revision = '4a0685f4a618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_blocked_tokens_id'), ['id'])

    with op.batch_alter_table('community_lists', schema=None) as batch_op:
        batch_op.drop_constraint('uq_community_lists_community_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_lists', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_community_lists_community_id', ['community_id'])

    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_blocked_tokens_id'), type_='unique')

    # ### end Alembic commands ###
