"""user-handle-2

Revision ID: 975c513fbd34
Revises: 3693bda32ddc
Create Date: 2022-11-25 00:34:59.102306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '975c513fbd34'
down_revision = '3693bda32ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_communities_users_avatar_id_files', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_communities_users_avatar_id_files'), 'files', ['avatar_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('dark_theme')
        batch_op.drop_column('bio')
        batch_op.drop_column('group')
        batch_op.drop_column('avatar')
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('avatar', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"topType": 0, "accessoriesType": 0, "hairColor": 0, "facialHairType": 0, "clotheType": 0, "eyeType": 0, "eyebrowType": 0, "mouthType": 0, "skinColor": 0, "bgcolor": 0}\'::json'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('group', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dark_theme', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('communities_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_communities_users_avatar_id_files'), type_='foreignkey')
        batch_op.create_foreign_key('fk_communities_users_avatar_id_files', 'files', ['avatar_id'], ['id'])

    # ### end Alembic commands ###
