"""user-avatar-chage-1

Revision ID: ab118d9db832
Revises: af277a67415b
Create Date: 2022-05-30 13:58:11.022138

"""
import json

import sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab118d9db832'
down_revision = 'af277a67415b'
branch_labels = None
depends_on = None

DEFAULT_AVATAR: dict = {  # noqa: WPS407
    "topType": 0,
    "accessoriesType": 0,
    "hairColor": 0,
    "facialHairType": 0,
    "clotheType": 0,
    "eyeType": 0,
    "eyebrowType": 0,
    "mouthType": 0,
    "skinColor": 0,
    "bgcolor": 0,
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.JSON(), nullable=False, server_default=sqlalchemy.text(f"'{json.dumps(DEFAULT_AVATAR)}'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
