"""user-avatar-chage-1

Revision ID: af277a67415b
Revises: 1c8e7a53e376
Create Date: 2022-05-30 13:57:41.540452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'af277a67415b'
down_revision = '1c8e7a53e376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
