"""communities-base-fix

Revision ID: d4d0629f8fb6
Revises: 435f3661fd58
Create Date: 2022-04-22 02:55:27.836666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d0629f8fb6'
down_revision = '435f3661fd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_foreign_key("feedbacks.123", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint("feedbacks.123", type_='foreignkey')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
