"""soft-delete

Revision ID: e47946082c0a
Revises: 7250fb010703
Create Date: 2023-04-09 16:30:34.524306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47946082c0a'
down_revision = '7250fb010703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cs_posts', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cs_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cs_tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('cs_tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('cs_roles', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('cs_posts', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('communities_users', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
