"""token-block-list-rename

Revision ID: f97329c355f9
Revises: 64b239c3d2ae
Create Date: 2022-08-16 22:20:36.434030

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f97329c355f9'
down_revision = '64b239c3d2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('blocked_tokens', 'token_block_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('token_block_list', 'blocked_tokens')
    # ### end Alembic commands ###
