name: Common Pipeline Steps

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      cache:
        type: boolean
        required: false
        default: true
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      - id: install
        name: Install Requirements
        run: pip install -r requirements.txt

      - id: flake8
        name: Run flake8
        run: flake8 --config=setup.cfg xieffect

      - name: Run pytest
        if: success() || (failure() && steps.install.conclusion == 'success')
        run: |
          cd xieffect
          pytest

      - name: Generate docs
        run: |
          cd xieffect
          flask form-sio-docs

      - name: Upload docs to artifact
        uses: actions/upload-artifact@v3
        with:
          name: async-api.json
          path: ./files/async-api.json
          retention-days: 1

  build:
    if: inputs.cache == true
    needs: prepare
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build.yml@main
    with:
      tag: flask-prod
    secrets: inherit

  build-nocache:
    if: inputs.cache == false
    needs: prepare
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build-nocache.yml@main
    with:
      tag: flask-prod
    secrets: inherit

  docs:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Download async-api.json from artifacts
        uses: actions/download-artifact@v3
        with:
          name: async-api.json
          path: ./

      - name: Generate docs
        uses: niqzart/ffs-devops/generate-asyncapi@main
        with:
          template: "@asyncapi/html-template"
          input: ./async-api.json
          output: -o ./sio-doc/
          parameters: -p singleFile=true

      - name: Upload docs to artifact
        uses: actions/upload-artifact@v3
        with:
          name: sio-doc
          path: ./sio-doc/index.html
          retention-days: 1
