name: Common Pipeline Steps

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      database:
        type: boolean
        required: false
        default: true
      coverage:
        type: boolean
        required: false
        default: true
      cache:
        type: boolean
        required: false
        default: true
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      DB_LINK: ${{ inputs.database && 'postgresql+psycopg2://test:test@localhost:5432/test' || 'sqlite:///app.db' }}

    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Requirements
        id: install
        run: pip install -r requirements.txt

      - name: Upgrade database to latest migration
        id: alembic-upgrade
        if: inputs.database
        working-directory: xieffect
        run: alembic upgrade head

      - name: Check that database is up to date with code
        id: alembic-revision
        if: inputs.database
        working-directory: xieffect
        run: |
          alembic revision --autogenerate -m "test" --rev-id 0
          if [ $(cat ./alembic/versions/0_test.py | wc -l) -ne 28 ]; then 
            exit 1
          fi

      - name: Run pytest
        run: pytest xieffect -p no:cacheprovider --cov=. --cov-fail-under=0

      - name: Report test coverage
        if: inputs.coverage
        run: coverage report

      - name: Run flake8
        id: flake8
        if: success() || (failure() && steps.install.conclusion == 'success')
        run: flake8 --config=setup.cfg xieffect

      - name: Check import ordering with isort
        id: isort
        if: success() || (failure() && steps.install.conclusion == 'success')
        run: isort xieffect --check --diff

      - name: Check formatting ordering with black
        id: black
        if: success() || (failure() && steps.install.conclusion == 'success')
        run: black xieffect --check --diff --extend-exclude "alembic|test|moderation"

      - name: Generate docs
        working-directory: xieffect
        run: flask form-sio-docs

      - name: Upload docs to artifact
        uses: actions/upload-artifact@v3
        with:
          name: async-api.json
          path: ./files/async-api.json
          retention-days: 1

  build:
    if: inputs.cache == true
    needs: prepare
    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit

  build-nocache:
    if: inputs.cache == false
    needs: prepare
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build-nocache.yml@main
    with:
      tag: ${{inputs.tag}}
    secrets: inherit

  docs:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Download async-api.json from artifacts
        uses: actions/download-artifact@v3
        with:
          name: async-api.json
          path: ./

      - name: Generate docs
        uses: niqzart/ffs-devops/generate-asyncapi@main
        with:
          template: "@asyncapi/html-template"
          input: ./async-api.json
          output: -o ./sio-doc/
          parameters: -p singleFile=true

      - name: Upload docs to artifact
        uses: actions/upload-artifact@v3
        with:
          name: sio-doc
          path: ./sio-doc/index.html
          retention-days: 1
