name: Development

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - master
      - prod

env:
  repo: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USERNAME }}

jobs:
  namer:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch_name.outputs.branch }}
      tag: ${{ steps.branch_name.outputs.tag }}
      base_branch: ${{ steps.branch_name.outputs.base_branch }}
      base_tag: ${{ steps.branch_name.outputs.base_tag }}

    steps:
      - name: Get tag & branch name
        id: branch_name
        run: |-
          branch=${{ github.event.pull_request.head.ref }}
          echo "branch=${branch}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT

          tag="flask-${branch////-}"
          echo "tag=${tag}"
          echo "tag=${tag}" >> $GITHUB_OUTPUT

          base_branch=${{ github.event.pull_request.base.ref }}
          echo "base_branch=${base_branch}"
          echo "base_branch=${base_branch}" >> $GITHUB_OUTPUT

          base_tag="flask-${base_branch////-}"
          echo "base_tag=${base_tag}"
          echo "base_tag=${base_tag}" >> $GITHUB_OUTPUT

  build_test_docs:
    needs: namer
    uses: ./.github/workflows/common-work.yml
    with:
      tag: ${{ needs.namer.outputs.tag }}
      base-tag: ${{ needs.namer.outputs.base_tag }}
      coverage: ${{ contains(github.event.pull_request.labels.*.name, 'ci:covered') }}
      database: ${{ contains(github.event.pull_request.labels.*.name, 'ci:migrated') }}
    secrets: inherit
