name: Feature Branch PR Pipeline

on:
  push:
    branches-ignore:
      - master  # see production.yml
      - prod  # see preproduction.yml

  workflow_dispatch:
    inputs:
      check_migrations:
        description: Migrations check
        type: boolean
        required: false
        default: false
      check_coverage:
        description: Coverage check
        type: boolean
        required: false
        default: false
      docker_tag:
        description: Docker tag override
        type: string
        required: false
      docker_base_tag:
        description: Base docker tag override
        type: string
        required: false

jobs:
  branch_name:
    runs-on: ubuntu-latest

    outputs:
      branch-name: ${{ steps.branch_name.outputs.branch }}
      docker-tag: ${{ steps.branch_name.outputs.tag }}

    steps:
      - name: Get tag & branch name
        id: branch_name
        run: |-
          result=${{ github.ref }}
          result=${result#refs/heads/}
          echo "branch=${result}"
          echo "branch=${result}" >> $GITHUB_OUTPUT
          result=${result////-}
          echo "tag=${result}"
          echo "tag=${result}" >> $GITHUB_OUTPUT

  build-test-docs:
    needs: branch_name
    uses: ./.github/workflows/common-work.yml
    with:
      tag: flask-${{ inputs.docker_tag || needs.branch_name.outputs.docker-tag }}
      base-tag: flask-${{ inputs.docker_base_tag || 'prod' }}
      database: ${{ inputs.check_migrations || false }}
      coverage: ${{ inputs.check_coverage || false }}
    secrets: inherit
