name: Production Pipeline

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-test-docs:
    uses: ./.github/workflows/common-work.yml
    with:
      tag: flask
    secrets: inherit

  deploy:
    needs: build-test-docs
    uses: xi-effect/xieffect-actions/.github/workflows/docker-deploy.yml@main
    with:
      images: flask
    secrets: inherit

  upload:
    needs: build-test-docs
    runs-on: ubuntu-latest

    steps:
      - name: Download sio-doc from artifacts
        uses: actions/download-artifact@v3
        with:
          name: sio-doc
          path: ./sio-doc/

      - name: Upload docs via SCP
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: root
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./sio-doc/*"
          target: "~/xieffect-core/sio-docs-new/"
          strip_components: 1
