name: Feature Branch PR Pipeline

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  build-test-docs:
    uses: ./.github/workflows/build.yml
    with:
      tag: flask-${{ github.event.issue.number }}
    secrets: inherit
