name: Feature Branch PR Pipeline

on:
  push:
    branches-ignore:
      - master
      - prod

  workflow_dispatch:

jobs:
  build-test-docs:
    uses: ./.github/workflows/common-work.yml
    with:
      tag: flask-${{ github.event.issue.number }}
      cache: false
    secrets: inherit
