name: Preproduction Pipeline

on:
  push:
    branches:
      - prod

  workflow_dispatch:

jobs:
  build-test-docs:
    uses: ./.github/workflows/common-work.yml
    with:
      tag: flask-prod
    secrets: inherit

  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: prod
          target_branch: master
          title: New Version
          body: |
            - [ ] version update
            - [ ] migration test
            - [ ] docker image check
