name: Production Pipeline

on:
  push:
    branches:
     - master

  workflow_dispatch:

jobs:
  build-test-docs:
    uses: ./.github/workflows/common-work.yml
    with:
      tag: flask
      base-tag: flask-prod
    secrets: inherit

  deploy:
    needs: build-test-docs
    uses: xi-effect/xi.actions/.github/workflows/docker-deploy.yml@main
    with:
      images: flask
    secrets: inherit

  upload:
    needs: build-test-docs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        envir:
          - staging
          - production
    environment:
      name: ${{ matrix.envir }}

    steps:
      - name: Download sio-doc from artifacts
        uses: actions/download-artifact@v3
        with:
          name: sio-doc
          path: ./sio-doc/

      - name: Upload docs via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./sio-doc/*
          target: ~/xieffect-core/sio-docs-new/
          strip_components: 1
          rm: true
